version: "3"

services:
  app:
    build: .docker/app
    container_name: codeflix-videos-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - APP_MODE=${APP_MODE}
      - CACHE_MODE=${CACHE_MODE}
      - OPCACHE_MODE=${OPCACHE_MODE}
    volumes:
      - .:/var/www
      - .docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
      - codeflix-microservice-rabbitmq_catalog-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: codeflix-videos-nginx
    entrypoint: dockerize -template /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf -wait tcp://app:9000 -timeout 40s nginx -g "daemon off;"
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=9000
    restart: always
    tty: true
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: codeflix-videos-db
    restart: always
    tty: true
    ports:
      - "3366:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:5.0-alpine
    container_name: codeflix-videos-redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  codeflix-microservice-rabbitmq_catalog-network:
    external: true
